version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: dev
  reviewers:
  - jordan1997
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
