language: android
env:
- SERVER_IP_ADDRESS=167.99.94.185
before_install:
- openssl aes-256-cbc -K $encrypted_3055159bc286_key -iv $encrypted_3055159bc286_iv
-in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_keyo
# test ssh connection for: https://github.com/dwyl/learn-travis/issues/42
- ssh -i ./deploy_key root@167.99.94.185 pwd

