language: android
android:
  components:
    - android-28
    - build-tools-27.0.3
addons:
  ssh_known_hosts: 167.99.94.185
  apt:
    packages:
    - sshpass

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew

# Run assemble and unit tests
script:
  - ./gradlew clean testDebugUnitTest dokka
deploy:
#  - provider: script
#    skip_cleanup: true
#    script: sshpass -e scp -v -o StrictHostKeyChecking=no -r androidgraphextension/build/dokka/ schoolhelper@167.99.94.185:/var/www/schoolhelper.tech/dev
#    on:
#      branch: dev
  - provider: script
    skip_cleanup: true
    script: sshpass -e scp -v -o StrictHostKeyChecking=no -r androidgraphextension/build/dokka/ schoolhelper@167.99.94.185:/var/www/schoolhelper.tech/master
    on:
      branch: master
