language: android
android:
  components:
    - android-28
    - build-tools-27.0.3

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew

# Run assemble and unit tests
script:
  - ./gradlew clean testDebugUnitTest jacocoTestDebugUnitTestReport createDebugUnitTestCoverageReport
after_success:
  - ls androidgraphextension/build/reports -all
  - mv androidgraphextension/build/reports/jacoco/createDebugUnitTestCoverageReport androidgraphextension/build/reports/jacoco/jacocoTestDebugUnitTestReport
  - mv androidgraphextension/build/reports/jacoco/jacocoTestDebugUnitTestReport/createDebugUnitTestCoverageReport.xml androidgraphextension/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
  - bash <(curl -s https://codecov.io/bash)