language: android
android:
  components:
    - android-28
    - build-tools-27.0.3

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod +x gradlew

# Run assemble and unit tests
script:
  - ./gradlew clean testDebugUnitTest createDebugUnitTestCoverageReport
script:
  # Renaming folder and files of reports so codecov.io can find it
  - mv app/build/reports/jacoco/createDebugUnitTestCoverageReport app/build/reports/jacoco/jacocoTestDebugUnitTestReport
  - mv app/build/reports/jacoco/jacocoTestDebugUnitTestReport/createDebugUnitTestCoverageReport.xml app/build/reports/jacoco/jacocoTestDebugUnitTestReport/jacocoTestDebugUnitTestReport.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)