version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: androidgraphextension/build/reports
          destination: reports
      - run:
          name: upload test coverage
          command: |
            if curl --silent --fail https://codecov.io/bash >codecov.sh; then
              bash <codecov.sh
            else
              echo skipping codecov -- script download error
            fi
      - store_test_results:
          path: androidgraphextension/build/test-results
      - run:
          name: Coverage
          command: <(curl -s https://codecov.io/bash)
