version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: pre-dependencies
          command: sudo pip install codecov
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew jacocoTestReportDebug
      - run:
          name: post-test
          command: codecov
      - store_artifacts:
          path: androidgraphextension/build/reports
          destination: reports
      - store_test_results:
          path: androidgraphextension/build/test-results