version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew jacocoTestDebugUnitTestReport
      # set up xml path for code climate
      - run:
          name: Set jacoco.xml path for code climate
          command: JACOCO_SOURCE_PATH=src/main/java ./cc-test-reporter format-coverage ./build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
      # upload coverage on code climate
      - run:
          name: Upload code climate report
          command: ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID
          when: on_success
      - store_artifacts:
          path: androidgraphextension/build/reports
          destination: reports
      - store_test_results:
          path: androidgraphextension/build/test-results