version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Install test reporter
          command: |
                curl -L -o "cc-test-reporter" "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64"
                sudo chmod +x ./cc-test-reporter
      - run:
          name: Run Tests
          command: ./gradlew testDebugUnitTest jacocoTestDebugUnitTestReport
      - store_artifacts:
          path: androidgraphextension/build/reports
          destination: reports
      - store_test_results:
          path: androidgraphextension/build/test-results