version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: pre-dependencies
          command: sudo pip install codecov
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Tests
          command: ./gradlew jacocoTestDebugUnitTestReport
      - run:
          name: post-test
          command: bash <(curl -s https://codecov.io/bash)